"""Timelapse use cases: list, download, and delete them all.

Timelapses live in Moonraker's "timelapse" root (generated by the
moonraker-timelapse component), manageable with the same generic file
endpoints that job_service uses for gcodes.
"""
from __future__ import annotations

from core.context import AppContext
from core.services.printer_service import PrinterNotFoundError

TIMELAPSE_ROOT = "timelapse"

# moonraker-timelapse stores its rendered videos in the same "timelapse"
# root as their thumbnail images (.jpg) — only the extensions below are
# actual playable video files.
_VIDEO_EXTENSIONS = (".mp4", ".mkv", ".webm", ".avi", ".mov")


def _is_video_file(path: str) -> bool:
    return path.lower().endswith(_VIDEO_EXTENSIONS)


def _client(ctx: AppContext, printer_name: str):
    if ctx.get_printer(printer_name) is None:
        raise PrinterNotFoundError(printer_name)
    return ctx.moonraker_client(printer_name)


async def list_timelapses(ctx: AppContext, printer_name: str) -> list[dict]:
    """Available timelapses, most recent first (by creation date).

    Filtered down to actual video files (drops thumbnail images that
    moonraker-timelapse stores alongside the renders in the same root) and
    deduplicated by path (some setups list the same file twice, e.g. via a
    symlinked/mirrored directory). Also drops 0-byte files: those are
    almost always leftovers from a render that failed or got interrupted
    mid-way (ffmpeg crash, Klipper restart during rendering, etc.) and are
    never playable.
    """
    files = await _client(ctx, printer_name).list_files(TIMELAPSE_ROOT)
    unique_by_path = {f["path"]: f for f in files}
    playable = [
        f
        for f in unique_by_path.values()
        if f.get("size", 0) > 0 and _is_video_file(f["path"])
    ]
    return sorted(playable, key=lambda f: f.get("modified", 0), reverse=True)


async def download_timelapse(ctx: AppContext, printer_name: str, filename: str) -> bytes:
    return await _client(ctx, printer_name).download_file(TIMELAPSE_ROOT, filename)


async def clear_timelapses(ctx: AppContext, printer_name: str) -> int:
    """Deletes all of the printer's timelapses. Returns how many it deleted."""
    client = _client(ctx, printer_name)
    files = await client.list_files(TIMELAPSE_ROOT)
    for f in files:
        await client.delete_file(TIMELAPSE_ROOT, f["path"])
    return len(files)
